apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "kubernetesgateways.networking.istio.io"
spec:
  group: "networking.istio.io"
  version: "v1alpha3"
  scope: "Namespaced"
  names:
     plural: "kubernetesgateways"
     singular: "kubernetesgateway"
     kind: "KubernetesGateway"
---
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "kuberneteshttproutes.networking.istio.io"
spec:
  group: "networking.istio.io"
  version: "v1alpha3"
  scope: "Namespaced"
  names:
     plural: "kuberneteshttproutes"
     singular: "kuberneteshttproute"
     kind: "KubernetesHTTPRoute"
---
apiVersion: networking.istio.io/v1alpha3
kind: KubernetesGateway
metadata:
  name: test
spec:
  class: istio
  listeners:
  - address: "howardjohn.local"
    port: 80
    protocols: ["HTTP"]
    routes: [test]
---
apiVersion: networking.istio.io/v1alpha3
kind: KubernetesHTTPRoute
metadata:
  name: test
spec:
  host: howardjohn.local
  rules:
  - path: "/"
    backend:
      service: httpbin
      port: 80