apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "kubernetesgateways.networking.istio.io"
spec:
  group: "networking.istio.io"
  version: "v1alpha3"
  scope: "Namespaced"
  names:
     plural: "kubernetesgateways"
     singular: "kubernetesgateway"
     kind: "KubernetesGateway"
---
apiVersion: networking.istio.io/v1alpha3
kind: KubernetesGateway
metadata:
  name: test
spec:
  class: foo