apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  components:
    ztunnel:
      k8s:
        overlays:
          - kind: DaemonSet
            name: ztunnel
            patches:
              - path: spec.template.spec.hostAliases
                value:
                  - ip: "10.42.0.2"
                    hostnames:
                      - "istiod.istio-system.svc"
    cni:
      k8s:
        env:
          - name: KUBERNETES_SERVICE_HOST
            value: 172.29.0.2
          - name: KUBERNETES_SERVICE_PORT
            value: "6443"
    pilot:
      enabled: true
      k8s:
        env:
          - name: KUBERNETES_SERVICE_HOST
            value: 172.29.0.2
          - name: KUBERNETES_SERVICE_PORT
            value: "6443"
  installPackagePath: manifests/
  meshConfig:
    accessLogFile: /dev/stdout
  profile: ambient
  values:
    cni:
      ambient:
        dnsCapture: true
      cniBinDir: /bin
      cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
      variant: ""
    global:
      variant: ""
    pilot:
      variant: ""
    ztunnel:
      variant: ""
      env:
        ISTIO_META_DNS_CAPTURE: "true"