apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: "sidecar-policy.example.com"
spec:
  matchConstraints:
    resourceRules:
      - apiGroups:   ["apps"]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  mutations:
    - patchType: "ApplyConfiguration"
      mutation: >
        Object{
            spec: Object.spec{
                containers: object.spec.containers{
                    object.spec.containers.filter(c, c.name == "sidecar")
                    .map(c, Object.spec.containers.item{
                        resources.foo: "1"
                    })
                }
            }
        }