// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/istio/servicev2/apis/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSuperServices implements SuperServiceInterface
type FakeSuperServices struct {
	Fake *FakeApisV1
	ns   string
}

var superservicesResource = v1.SchemeGroupVersion.WithResource("superservices")

var superservicesKind = v1.SchemeGroupVersion.WithKind("SuperService")

// Get takes name of the superService, and returns the corresponding superService object, and an error if there is any.
func (c *FakeSuperServices) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SuperService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(superservicesResource, c.ns, name), &v1.SuperService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SuperService), err
}

// List takes label and field selectors, and returns the list of SuperServices that match those selectors.
func (c *FakeSuperServices) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SuperServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(superservicesResource, superservicesKind, c.ns, opts), &v1.SuperServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.SuperServiceList{ListMeta: obj.(*v1.SuperServiceList).ListMeta}
	for _, item := range obj.(*v1.SuperServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested superServices.
func (c *FakeSuperServices) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(superservicesResource, c.ns, opts))

}

// Create takes the representation of a superService and creates it.  Returns the server's representation of the superService, and an error, if there is any.
func (c *FakeSuperServices) Create(ctx context.Context, superService *v1.SuperService, opts metav1.CreateOptions) (result *v1.SuperService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(superservicesResource, c.ns, superService), &v1.SuperService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SuperService), err
}

// Update takes the representation of a superService and updates it. Returns the server's representation of the superService, and an error, if there is any.
func (c *FakeSuperServices) Update(ctx context.Context, superService *v1.SuperService, opts metav1.UpdateOptions) (result *v1.SuperService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(superservicesResource, c.ns, superService), &v1.SuperService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SuperService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSuperServices) UpdateStatus(ctx context.Context, superService *v1.SuperService, opts metav1.UpdateOptions) (*v1.SuperService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(superservicesResource, "status", c.ns, superService), &v1.SuperService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SuperService), err
}

// Delete takes name of the superService and deletes it. Returns an error if one occurs.
func (c *FakeSuperServices) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(superservicesResource, c.ns, name, opts), &v1.SuperService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSuperServices) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(superservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.SuperServiceList{})
	return err
}

// Patch applies the patch and returns the patched superService.
func (c *FakeSuperServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SuperService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(superservicesResource, c.ns, name, pt, data, subresources...), &v1.SuperService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SuperService), err
}
