// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "istio.io/istio/servicev2/pkg/client/clientset/versioned/typed/apis/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeApisV1 struct {
	*testing.Fake
}

func (c *FakeApisV1) SuperServices(namespace string) v1.SuperServiceInterface {
	return &FakeSuperServices{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeApisV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
