// Code generated by lister-gen. DO NOT EDIT.

package v1

// SuperServiceListerExpansion allows custom methods to be added to
// SuperServiceLister.
type SuperServiceListerExpansion interface{}

// SuperServiceNamespaceListerExpansion allows custom methods to be added to
// SuperServiceNamespaceLister.
type SuperServiceNamespaceListerExpansion interface{}
