apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: echo
  namespace: default
spec:
  parentRefs:
    - group: ""
      kind: Service
      name: echo
      port: 80
  rules:
    - backendRefs:
        - name: echo
          port: 80
---