apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  annotations:
    networking.istio.io/service-type: "ClusterIP"
spec:
  gatewayClassName: istio
  listeners:
{{ if false }}
  {{ range $port := .Ports }}
  - name: "https-{{.}}"
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    port: {{.}}
    tls:
      mode: Terminate
      options:
        "gateway.istio.io/tls-terminate-mode": ISTIO_MUTUAL
  {{ end }}
{{ else }}
  {{ range $port := .Ports }}
- name: "http-{{.}}"
  protocol: HTTP
  allowedRoutes:
    namespaces:
      from: Same
  port: {{.}}
  {{ end }}
{{ end }}

