apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "0"
      containers:
        - name: echo
          image: gcr.io/istio-testing/app:latest
          imagePullPolicy: IfNotPresent
          args:
            - --port=80
            - --port=443
            - --tls=443
            - --crt=/cert.crt
            - --key=/cert.key
          env:
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  annotations:
    istio.io/use-waypoint: "yes"
spec:
  selector:
    app: echo
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-route
spec:
  selector:
    matchLabels:
      app: echo-route
  template:
    metadata:
      labels:
        app: echo-route
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "0"
      containers:
        - name: echo
          image: gcr.io/istio-testing/app:latest
          imagePullPolicy: IfNotPresent
          args:
            - --port=80
            - --port=443
            - --tls=443
            - --crt=/cert.crt
            - --key=/cert.key
          env:
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: echo-route
  annotations:
    istio.io/use-waypoint: "yes"
spec:
  selector:
    app: echo-route
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: echo-route
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: echo-route
  rules:
  - filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          add:
            - name: my-added-header
              value: added-value
    backendRefs:
      - name: echo-route
        port: 80