apiVersion: networking.istio.io/v1alpha3
kind: Waypoint
metadata:
  name: default
  namespace: default
spec:
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: echo
  namespace: default
spec:
  parentRefs:
    - group: ""
      kind: Service
      name: echo
      port: 80
  rules:
    - backendRefs:
        - name: echo
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hyper
  namespace: default
spec:
  parentRefs:
    - group: ""
      kind: Service
      name: hyper
      port: 80
  rules:
    - backendRefs:
        - name: hyper
          port: 80
---