apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{.Waypoint.Name}}
  namespace: {{.Waypoint.Namespace}}
  annotations:
    networking.istio.io/service-type: "ClusterIP"
  ownerReferences:
    - apiVersion: "networking.istio.io/v1alpha3"
      kind: "Waypoint"
      name: "{{.Waypoint.Name}}"
      uid: "{{.Waypoint.UID}}"
spec:
  gatewayClassName: {{.Class}}
  listeners:
{{ if false }}
  {{ range $port := .Ports }}
  - name: "https-{{.}}"
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    port: {{.}}
    tls:
      mode: Terminate
      options:
        "gateway.istio.io/tls-terminate-mode": ISTIO_MUTUAL
  {{ end }}
{{ else }}
  {{ range $port := .Ports }}
  - name: "http-{{.}}"
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
    port: {{.}}
    {{ end }}
{{ end }}

