apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{.Name}}-mesh-internal
  namespace: {{.Namespace}}
  ownerReferences:
    - apiVersion: "{{.APIVersion}}"
      kind: "{{.Kind }}"
      name: "{{.Name}}"
      uid: "{{.UID}}"
spec:
  parentRefs:
    - name: waypoint
  hostnames: {{.Hostnames | toJson|indent 2}}
  rules: {{.Spec.Rules | toJson | indent 2}}