apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{.Name}}-mesh-internal
  namespace: {{.Namespace}}
  ownerReferences:
    - apiVersion: "gateway.networking.k8s.io/v1beta1"
      kind: "HTTPRoute"
      name: "{{.Name}}"
      uid: "{{.UID}}"
spec:
  parentRefs:
  - name: {{.Waypoint.Name}}
#  {{ range $pr := .Spec.ParentRefs }}
#    - name: waypoint
#    {{with $pr.Port}}
#      port: {{.}}
#    {{ end }}
#  {{ end }}
  hostnames: {{.Hostnames | toJson|indent 2}}
  rules: {{.Spec.Rules | toJson | indent 2}}