apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{.Name}}-waypoint-mirror
  namespace: {{.Namespace}}
  ownerReferences:
    - apiVersion: "gateway.networking.k8s.io/v1beta1"
      kind: "HTTPRoute"
      name: "{{.Name}}"
      uid: "{{.UID}}"
spec:
  parentRefs:
  {{ range $port := .ServicePorts }}
    - name: {{$.Name}}-waypoint
    {{with $port}}
      sectionName: port-{{.}}
    {{ end }}
  {{ end }}
  rules: {{.Spec.Rules | toJson | indent 2}}