{{ range $port := .Ports }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{$.Name}}-waypoint-default-{{.}}
  namespace: {{$.Namespace}}
  ownerReferences:
    - apiVersion: "gateway.networking.k8s.io/v1beta1"
      kind: "Gateway"
      name: "{{$.Gateway.Name}}"
      uid: "{{$.Gateway.UID}}"
spec:
  parentRefs:
  - name: {{$.Gateway.Name}}
    sectionName: port-{{.}}
  rules:
  - backendRefs:
      - name: {{$.Name}}
        port: {{.}}
---
{{ end }}