apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  ownerReferences:
    - apiVersion: "networking.istio.io/v1alpha3"
      kind: "Waypoint"
      name: "{{.Waypoint.Name}}"
      uid: "{{.Waypoint.UID}}"
spec:
  ports:
  {{ range $port := .Ports }}
  - name: "http-{{.}}"
    port: {{.}}
  {{ end }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  ownerReferences:
    - apiVersion: "networking.istio.io/v1alpha3"
      kind: "Waypoint"
      name: "{{.Waypoint.Name}}"
      uid: "{{.Waypoint.UID}}"
subsets:
  - addresses:
      - ip: {{.Address}}
    ports:
    {{ range $port := .Ports }}
    - name: "http-{{.}}"
      port: {{.}}
    {{ end }}
