apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  ports:
  {{ range $port := .Ports }}
  - name: "port-{{.}}"
    port: {{.}}
  {{ end }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
subsets:
  - addresses:
      - ip: {{.Address}}
    ports:
    {{ range $port := .Ports }}
    - name: "port-{{.}}"
      port: {{.}}
    {{ end }}
