apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
  labels:
    app: sidecar-injector
webhooks:
  - name: sidecar-injector.istio.io
    clientConfig:
      url: https://istiod.howardjohn-mc.qualistio.org/inject
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        istio-injection: enabled
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: istiod-istio-system
  labels:
    app: istiod
    release: istio
    istio: istiod
webhooks:
  - name: validation.istio.io
    clientConfig:
      url: https://istiod.howardjohn-mc.qualistio.org/validate
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - config.istio.io
          - rbac.istio.io
          - security.istio.io
          - authentication.istio.io
          - networking.istio.io
        apiVersions:
          - "*"
        resources:
          - "*"
    failurePolicy: Fail
    sideEffects: None
