// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "istio.io/istio/servicev2/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// SuperServices returns a SuperServiceInformer.
	SuperServices() SuperServiceInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// SuperServices returns a SuperServiceInformer.
func (v *version) SuperServices() SuperServiceInformer {
	return &superServiceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
