// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	apisv1 "istio.io/istio/servicev2/apis/v1"
	versioned "istio.io/istio/servicev2/pkg/client/clientset/versioned"
	internalinterfaces "istio.io/istio/servicev2/pkg/client/informers/externalversions/internalinterfaces"
	v1 "istio.io/istio/servicev2/pkg/client/listers/apis/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SuperServiceInformer provides access to a shared informer and lister for
// SuperServices.
type SuperServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SuperServiceLister
}

type superServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSuperServiceInformer constructs a new informer for SuperService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSuperServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSuperServiceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSuperServiceInformer constructs a new informer for SuperService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSuperServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1().SuperServices(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1().SuperServices(namespace).Watch(context.TODO(), options)
			},
		},
		&apisv1.SuperService{},
		resyncPeriod,
		indexers,
	)
}

func (f *superServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSuperServiceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *superServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisv1.SuperService{}, f.defaultInformer)
}

func (f *superServiceInformer) Lister() v1.SuperServiceLister {
	return v1.NewSuperServiceLister(f.Informer().GetIndexer())
}
