{{- if and .Values.pilot.autoscaleEnabled .Values.pilot.autoscaleMin .Values.pilot.autoscaleMax }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
{{- if .Values.global.revision }}
  name: istiod-{{ .Values.global.revision }}
{{- else }}
  name: istio-pilot
{{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: pilot
    release: {{ .Release.Name }}
spec:
  maxReplicas: {{ .Values.pilot.autoscaleMax }}
  minReplicas: {{ .Values.pilot.autoscaleMin }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
  {{- if .Values.global.revision }}
    name: istiod-{{ .Values.global.revision }}
  {{- else }}
    name: istiod
  {{- end }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.pilot.cpu.targetAverageUtilization }}
---
{{- end }}
