{{- if .Values.global.istiod.enabled }}
{{- if not .Values.global.operatorManageWebhooks }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
{{- if .Values.global.revision }}
  name: istiod-{{ .Values.global.revision }}
{{- else }}
  name: istiod
{{- end }}
  labels:
    app: istiod
{{- if .Values.global.revision }}
    istio.io/rev: {{.Values.global.revision}}
{{- end }}
webhooks:
  - name: sidecar-injector.istio.io
    clientConfig:
      service:
      {{- if .Values.global.revision }}
        name: istiod-{{ .Values.global.revision }}
      {{- else }}
        name: istiod
      {{- end }}
        namespace: {{ .Release.Namespace }}
        path: "/inject"
      caBundle: ""
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
{{- if .Values.sidecarInjectorWebhook.enableNamespacesByDefault }}
      matchExpressions:
      - key: name
        operator: NotIn
        values:
        - {{ .Release.Namespace }}
      - key: istio-injection
        operator: NotIn
        values:
        - disabled
      - key: istio-env
        operator: DoesNotExist
      - key: istio.io/rev
        operator: DoesNotExist
{{- else if .Values.global.revision }}
      matchExpressions:
      - key: istio-injection
        operator: DoesNotExist
      - key: istio.io/rev
        operator: In
        values:
        - {{ .Values.global.revision }}
{{- else if eq .Values.sidecarInjectorWebhook.injectLabel "istio-injection" }}
      matchLabels:
        istio-injection: enabled
{{- else }}
      matchLabels:
        istio-env: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.sidecarInjectorWebhook.objectSelector.enabled }}
    objectSelector:
{{- if .Values.sidecarInjectorWebhook.objectSelector.autoInject }}
      matchExpressions:
      - key: "sidecar.istio.io/inject"
        operator: NotIn
        values:
        - "false"
{{- else }}
      matchLabels:
        "sidecar.istio.io/inject": "true"
{{- end }}
{{- end }}
{{- end }}
{{- end }}