{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
{{- if .Values.global.revision }}
  name: istiod-{{ .Values.global.revision }}
{{- else }}
  name: istio-pilot
{{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: pilot
    release: {{ .Release.Name }}
    istio: pilot
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: pilot
{{- if .Values.global.revision }}
      istio.io/rev: {{.Values.global.revision}}
{{- else }}
      release: {{ .Release.Name }}
      istio: pilot
{{- end }}
---
{{- end }}
