apiVersion: v1
kind: Service
metadata:
  name: istio-pilot{{ .Values.version }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: pilot
    release: {{ .Release.Name }}
    istio: pilot
spec:
  ports:
  - port: 15010
    name: grpc-xds # direct
  - port: 15011
    name: https-xds # mTLS
  - port: 15012
    name: https-dns # mTLS with k8s-signed cert
  - port: 8080
    name: http-legacy-discovery # direct
  - port: 15014
    name: http-monitoring
{{- if .Values.global.istiod.enabled }}
  - port: 443
    name: https-webhook # validation and injection
    targetPort: 15017
{{- end }}
  selector:
    {{- if .Values.global.revision }}
    app: pilot
    istio.io/rev: {{.Values.global.revision}}
    {{- else if ne .Values.version ""}}
    app: pilot
    version: {{ .Values.version }}
    {{- else }}
    # Label used by the 'default' service. For versioned deployments we match with app and version.
    # This avoids default deployment picking the canary
    istio: pilot
    {{- end }}
---
{{- if .Values.global.istiod.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: {{ .Release.Namespace }}
  labels:
    app: istiod
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 15012
      name: https-dns # mTLS with k8s-signed cert
    - port: 443
      name: https-webhook # validation and injection
      targetPort: 15017
  selector:
    {{- if .Values.global.revision }}
    app: pilot
    istio.io/rev: {{.Values.global.revision}}
    {{- else if ne .Values.version ""}}
    app: pilot
    version: {{ .Values.version }}
    {{- else }}
    # Label used by the 'default' service. For versioned deployments we match with app and version.
    # This avoids default deployment picking the canary
    istio: pilot
    {{- end }}
---
{{- end }}